Remove final keyword from RedisCache
subjective-php/psr-cache-redis pull request #5
Opened 2018-02-15 07:52 UTC by arnaspet

Fixes # .

#### What does this PR do?
Well, first of all hi again, im still using your library and needed few bugfixes, and i encouter a final keyword. I dont think there should be `final` keywords in libraries at all. Especially in classes which should be used outside your library ( not internal ones ).

2018-02-21 07:01 UTC, arnaspet commented
@chadicus  ?

2018-02-26 16:11 UTC, chadicus commented on src/RedisCache.php
> +class RedisCache implements CacheInterface
What is the reasoning for the removal of the final keyword?

2018-02-26 16:14 UTC, chadicus commented
If you remove the commit which removes the `final` keyword, i can get this merged

2018-02-26 17:31 UTC, chadicus requested changes
Please remove the commit which removes the `final` keyword.

2018-02-27 18:40 UTC, chadicus commented
@arnaspet the removal of `exists` functionality was merged with PR #8  and released with v0.1.1.  If you want to discuss the removal of the `final` keyword, please open a new issue.

2018-02-27 18:40 UTC, closed without merging